version: '3.3'
services:
    tomcat:
        image: 'tomcat:9-jdk11'
        restart: on-failure:3
        ports:
        - '8888:8080'
        volumes:
        - ./fuseki/jena-fuseki-war-4.6.1.war:/usr/local/tomcat/webapps/fuseki.war
        - ./VaadinUI/CottageBookingVaadinUI.war:/usr/local/tomcat/webapps/ui.war
        - ./JenaDB/CottageBookingJenaDB.war:/usr/local/tomcat/webapps/db.war
        - ./config.ttl:/etc/fuseki/config.ttl
        - ./fuseki/databases/:/etc/fuseki/databases/